Hw03 mongodb
Filatov44/nodejs-homework-rest-api pull request #2
Opened 2022-12-20 17:09 UTC by Filatov44

Добрый вечер. Проверьте пожалуйста)

2022-12-21 07:37 UTC, BohdanGres requested changes
оскільки в тебе валідація в мідлварах то можна для апдейтів використовувати 1 контролер бо вони однакові, а так все супер!

2022-12-21 07:37 UTC, BohdanGres commented on middlewares/validateParams.js
> -const validateParams = (schema) => {
цей варіант був кращим бо його можна було налаштовувати на різні схеми

2022-12-21 09:08 UTC, Filatov44 commented
Переробив  зауваження.  Зробив 1 контролер для апдейтів , та зробив валідацію вхідних даних параметрів через validateParams(schemas.JoiSchemaParams) через бібліотеку Joi, а також валідацію параметра contactId на стороні бази даних через validateParamsForMangoose

2022-12-22 06:17 UTC, BohdanGres approved these changes

2022-12-28 11:24 UTC, merged